
import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import { Providers } from '@/redux/providers'

const inter = Roboto({
  weight: ["100", "300", '400', "500", '700', "900"],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
  return (
    <html lang="en" className='dark' >
      <body className={inter.className}>
          <Providers>
            <Navbar />
            {children}
          </Providers>
      </body>
    </html>

  )
}
